import 'dart:ui';

List l = [];
List m = [];
List n = [];
List button1 = [];
List l2 = [];

Map sets = {
  0: [19.992118, 99.860694],
  1: [20.044707, 99.828704],
  2: [20.064509, 99.811011],
  3: [20.027004, 99.844637],
  4: [20.033889, 99.836202],
  5: [20.033839, 99.855696],
  6: [20.015930, 99.520620],
  7: [20.017781, 99.882237],
  8: [20.019234, 99.889824],
  9: [19.992970, 99.861781],
  10: [19.992596, 99.859079],
  11: [19.994223, 99.864782],
  12: [19.992283, 99.863845],
  13: [20.031752, 99.872231],
  14: [20.032092, 99.873869],
  15: [19.993666, 99.864708],
};

const List u = [
  images,
  images1,
  images2,
  images3,
  images4,
  images5,
  images6,
  images7,
  images8,
  images9,
  images10,
  images11,
  images12,
  images13,
  images14,
  images15,
];

const List<String> imagess = [
  "assets/images/im/imagess/000.jpg",
  "assets/images/im/imagess/001.jpg",
  "assets/images/im/imagess/002.jpg",
  "assets/images/im/imagess/003.jpg",
  "assets/images/im/imagess/004.jpg",
  "assets/images/im/imagess/005.jpg",
  "assets/images/im/imagess/006.jpg",
  "assets/images/im/imagess/007.jpg",
  "assets/images/im/imagess/008.jpg",
  "assets/images/im/imagess/009.jpg",
  "assets/images/im/imagess/010.jpg",
  "assets/images/im/imagess/011.jpg",
  "assets/images/im/imagess/012.jpg",
  "assets/images/im/imagess/013.jpg",
  "assets/images/im/imagess/014.jpg",
  "assets/images/im/imagess/015.jpg",
  // target
];

const List<String> images = [
  // target
  "assets/images/im/images/000.jpg",
  "assets/images/im/images/001.jpg",
  "assets/images/im/images/002.jpg",
  "assets/images/im/images/003.jpg",
  "assets/images/im/images/004.jpg",
  "assets/images/im/images/005.jpg",
  "assets/images/im/images/006.jpg",
  "assets/images/im/images/007.jpg",
  "assets/images/im/images/008.jpg",
  "assets/images/im/images/009.jpg",
  "assets/images/im/images/010.jpg",
  "assets/images/im/images/011.jpg",
  "assets/images/im/images/012.jpg",
  "assets/images/im/images/013.jpg",
  "assets/images/im/images/014.jpg",
  "assets/images/im/images/015.jpg",
  // target
];
const List<String> images1 = [
  "assets/images/im/images1/000.jpg",
  "assets/images/im/images1/001.jpg",
  "assets/images/im/images1/002.jpg",
  "assets/images/im/images1/003.jpg",
  "assets/images/im/images1/004.jpg",
  "assets/images/im/images1/005.jpg",
  "assets/images/im/images1/006.jpg",
  "assets/images/im/images1/007.jpg",
  // target
];
const List<String> images2 = [
  // target
  "assets/images/im/images2/000.jpg",
  "assets/images/im/images2/001.jpg",
  "assets/images/im/images2/002.jpg",
  "assets/images/im/images2/003.jpg",
  "assets/images/im/images2/004.jpg",
  "assets/images/im/images2/005.jpg",
  "assets/images/im/images2/006.jpg",
];
const List<String> images3 = [
  // target
  "assets/images/im/images3/000.jpg",
  "assets/images/im/images3/001.jpg",
  "assets/images/im/images3/002.jpg",
  "assets/images/im/images3/003.jpg",
  "assets/images/im/images3/004.jpg",
  "assets/images/im/images3/005.jpg",
  "assets/images/im/images3/006.jpg",
  "assets/images/im/images3/007.jpg",
  "assets/images/im/images3/008.jpg",
  "assets/images/im/images3/009.jpg",
  "assets/images/im/images3/010.jpg",
  "assets/images/im/images3/011.jpg",
  "assets/images/im/images3/012.jpg",
  "assets/images/im/images3/013.jpg",
  "assets/images/im/images3/014.jpg",
  "assets/images/im/images3/015.jpg",
  "assets/images/im/images3/016.jpg",
  "assets/images/im/images3/017.jpg",
];
const List<String> images4 = [
  // target
  "assets/images/im/images4/000.jpg",
  "assets/images/im/images4/001.jpg",
  "assets/images/im/images4/002.jpg",
  "assets/images/im/images4/003.jpg",
  "assets/images/im/images4/004.jpg",
  "assets/images/im/images4/005.jpg",
  "assets/images/im/images4/006.jpg",
  "assets/images/im/images4/007.jpg",
  "assets/images/im/images4/008.jpg",
  "assets/images/im/images4/009.jpg",
  "assets/images/im/images4/010.jpg",
  "assets/images/im/images4/011.jpg",
  "assets/images/im/images4/012.jpg",
  "assets/images/im/images4/013.jpg",
  "assets/images/im/images4/014.jpg",
  "assets/images/im/images4/015.jpg",
  "assets/images/im/images4/016.jpg",
  "assets/images/im/images4/017.jpg",
  "assets/images/im/images4/018.jpg",
  "assets/images/im/images4/019.jpg",
];
const List<String> images5 = [
  // target
  "assets/images/im/images5/000.jpg",
  "assets/images/im/images5/001.jpg",
  "assets/images/im/images5/002.jpg",
  "assets/images/im/images5/003.jpg",
  "assets/images/im/images5/004.jpg",
  "assets/images/im/images5/005.jpg",
  "assets/images/im/images5/006.jpg",
  "assets/images/im/images5/007.jpg",
  "assets/images/im/images5/008.jpg",
  "assets/images/im/images5/009.jpg",
  "assets/images/im/images5/010.jpg",
  "assets/images/im/images5/011.jpg",
  "assets/images/im/images5/012.jpg",
  "assets/images/im/images5/013.jpg",
  "assets/images/im/images5/014.jpg",
  "assets/images/im/images5/015.jpg",
  "assets/images/im/images5/016.jpg",
  "assets/images/im/images5/017.jpg",

];
const List<String> images6 = [
  // target
  "assets/images/im/images6/000.jpg",
  "assets/images/im/images6/001.jpg",
  "assets/images/im/images6/002.jpg",
  "assets/images/im/images6/003.jpg",
  "assets/images/im/images6/004.jpg",
  "assets/images/im/images6/005.jpg",
  "assets/images/im/images6/006.jpg",


];
const List<String> images7 = [
  // target
  "assets/images/im/images7/000.jpg",
  "assets/images/im/images7/001.jpg",
  "assets/images/im/images7/002.jpg",
  "assets/images/im/images7/003.jpg",
  "assets/images/im/images7/004.jpg",
  "assets/images/im/images7/005.jpg",
  "assets/images/im/images7/006.jpg",
  "assets/images/im/images7/007.jpg",
  "assets/images/im/images7/008.jpg",
  "assets/images/im/images7/009.jpg",
  "assets/images/im/images7/010.jpg",
  "assets/images/im/images7/011.jpg",
  "assets/images/im/images7/012.jpg",
  "assets/images/im/images7/013.jpg",
  "assets/images/im/images7/014.jpg",
  "assets/images/im/images7/015.jpg",
  "assets/images/im/images7/016.jpg",
  "assets/images/im/images7/017.jpg",
];
const List<String> images8 = [
  // target
  "assets/images/im/images8/000.jpg",
  "assets/images/im/images8/001.jpg",
  "assets/images/im/images8/002.jpg",
  "assets/images/im/images8/003.jpg",
  "assets/images/im/images8/004.jpg",
  "assets/images/im/images8/005.jpg",
  "assets/images/im/images8/006.jpg",
  "assets/images/im/images8/007.jpg",
  "assets/images/im/images8/008.jpg",
  "assets/images/im/images8/009.jpg",
  "assets/images/im/images8/010.jpg",
  "assets/images/im/images8/011.jpg",
  "assets/images/im/images8/012.jpg",
  "assets/images/im/images8/013.jpg",
  "assets/images/im/images8/014.jpg",
  "assets/images/im/images8/015.jpg",
  "assets/images/im/images8/016.jpg",
  "assets/images/im/images8/017.jpg",
];
const List<String> images9 = [
  // target
  "assets/images/im/images9/000.jpg",
  "assets/images/im/images9/001.jpg",
  "assets/images/im/images9/002.jpg",
  "assets/images/im/images9/003.jpg",
  "assets/images/im/images9/004.jpg",
  "assets/images/im/images9/005.jpg",
  "assets/images/im/images9/006.jpg",
  "assets/images/im/images9/007.jpg",
  "assets/images/im/images9/008.jpg",
  "assets/images/im/images9/009.jpg",
  "assets/images/im/images9/010.jpg",
  "assets/images/im/images9/011.jpg",
  "assets/images/im/images9/012.jpg",
  "assets/images/im/images9/013.jpg",
  "assets/images/im/images9/014.jpg",
  "assets/images/im/images9/015.jpg",
  "assets/images/im/images9/016.jpg",
  "assets/images/im/images9/017.jpg",
  "assets/images/im/images9/018.jpg",
  "assets/images/im/images9/019.jpg",
  "assets/images/im/images9/020.jpg",
];
const List<String> images10 = [
  // target
  "assets/images/im/images10/000.jpg",
  "assets/images/im/images10/001.jpg",
  "assets/images/im/images10/002.jpg",
  "assets/images/im/images10/003.jpg",
  "assets/images/im/images10/004.jpg",
  "assets/images/im/images10/005.jpg",
  "assets/images/im/images10/006.jpg",
  "assets/images/im/images10/007.jpg",
  "assets/images/im/images10/008.jpg",
  "assets/images/im/images10/009.jpg",
  "assets/images/im/images10/010.jpg",
  "assets/images/im/images10/011.jpg",

];
const List<String> images11 = [
  // target
  "assets/images/im/images11/000.jpg",
  "assets/images/im/images11/001.jpg",
  "assets/images/im/images11/002.jpg",
  "assets/images/im/images11/003.jpg",
  "assets/images/im/images11/004.jpg",
  "assets/images/im/images11/005.jpg",
  "assets/images/im/images11/006.jpg",
  "assets/images/im/images11/007.jpg",
  "assets/images/im/images11/008.jpg",
  "assets/images/im/images11/009.jpg",
  "assets/images/im/images11/010.jpg",
  "assets/images/im/images11/011.jpg",
  "assets/images/im/images11/012.jpg",
  "assets/images/im/images11/013.jpg",
  "assets/images/im/images11/014.jpg",

];
const List<String> images12 = [
  // target
  "assets/images/im/images12/000.jpg",
  "assets/images/im/images12/001.jpg",
  "assets/images/im/images12/002.jpg",
  "assets/images/im/images12/003.jpg",
  "assets/images/im/images12/004.jpg",
  "assets/images/im/images12/005.jpg",
  "assets/images/im/images12/006.jpg",
  "assets/images/im/images12/007.jpg",
  "assets/images/im/images12/008.jpg",
  "assets/images/im/images12/009.jpg",
  "assets/images/im/images12/010.jpg",
  "assets/images/im/images12/011.jpg",
  "assets/images/im/images12/012.jpg",
  "assets/images/im/images12/013.jpg",
];
const List<String> images13 = [
  // target
  "assets/images/im/images13/000.jpg",
  "assets/images/im/images13/001.jpg",
  "assets/images/im/images13/002.jpg",
  "assets/images/im/images13/003.jpg",
  "assets/images/im/images13/004.jpg",
  "assets/images/im/images13/005.jpg",
  "assets/images/im/images13/006.jpg",
  "assets/images/im/images13/007.jpg",
  "assets/images/im/images13/008.jpg",
  "assets/images/im/images13/009.jpg",
  "assets/images/im/images13/010.jpg",
  "assets/images/im/images13/011.jpg",
  "assets/images/im/images13/012.jpg",

];
const List<String> images14 = [
  // target
  "assets/images/im/images14/000.jpg",
  "assets/images/im/images14/001.jpg",
  "assets/images/im/images14/002.jpg",
  "assets/images/im/images14/003.jpg",
  "assets/images/im/images14/004.jpg",
  "assets/images/im/images14/005.jpg",
  "assets/images/im/images14/006.jpg",
  "assets/images/im/images14/007.jpg",
  "assets/images/im/images14/008.jpg",
  "assets/images/im/images14/009.jpg",
  "assets/images/im/images14/010.jpg",
  "assets/images/im/images14/011.jpg",
  "assets/images/im/images14/012.jpg",
  "assets/images/im/images14/013.jpg",
];
const List<String> images15 = [
  // target
  "assets/images/im/images15/000.jpg",
  "assets/images/im/images15/001.jpg",
  "assets/images/im/images15/002.jpg",
  "assets/images/im/images15/003.jpg",
  "assets/images/im/images15/004.jpg",
  "assets/images/im/images15/005.jpg",
  "assets/images/im/images15/006.jpg",
  "assets/images/im/images15/007.jpg",
  "assets/images/im/images15/008.jpg",
  "assets/images/im/images15/009.jpg",
  "assets/images/im/images15/010.jpg",
  "assets/images/im/images15/011.jpg",
  "assets/images/im/images15/012.jpg",
  "assets/images/im/images15/013.jpg",
  "assets/images/im/images15/014.jpg",
  "assets/images/im/images15/015.jpg",
  "assets/images/im/images15/016.jpg",
  "assets/images/im/images15/017.jpg",
  "assets/images/im/images15/018.jpg",
];

const List<String> hardtext = [
  //เเครอด ผัก ผมไม้
  "พิพิธภัณฑ์บ้านดำ",
  "น้ำตกนางแลใน",
  "นาขั้นบันได",
  "ร้านทุ่งเคียงดอย & เคียงดอยคาเฟ่",
  "สวนสตอเบอร์รี่ชมดอย โฮมสเตย์",
  "โฮงฮอมผญ๋า โฮงยาหมอเมืองล้านนา..",
  "สวนคุณปู่สับปะรดอินทรีย์",
  "เครื่องปั้นดินเผาดอยดินแดง",
  "ชุมชุนบ้านป่าอ้อ5ชนเผ่ากระเหรี่ยงคอยาว",
  "ร้าน Some Sunday Magic",
  "ร้าน Give Green Farm House..",
  "ร้าน Di Angello Pizzeria (ดิแอง..",
  "ร้าน Box Cafe'",
  "ร้าน Pasang",
  "ร้านไก่ย่างภูแล",
  "ร้าน ๙ Cafe' Chiang Rai",
];
const List<String> hardtext1 = [
  //เเครอด ผัก ผมไม้
  "พิพิธภัณฑ์บ้านดำ",
  "น้ำตกนางแลใน",
  "นาขั้นบันได",
  "ร้านทุ่งเคียงดอย & เคียงดอยคาเฟ่",
  "สวนสตอเบอร์รี่ชมดอย โฮมสเตย์",
  "โฮงฮอมผญ๋า โฮงยาหมอเมืองล้านนา..",
  "สวนคุณปู่สับปะรดอินทรีย์",
  "เครื่องปั้นดินเผาดอยดินแดง",
  "ชุมชุนบ้านป่าอ้อ5ชนเผ่ากระเหรี่ยงคอยาว",
  "ร้าน Some Sunday Magic",
  "ร้าน Give Green Farm House..",
  "ร้าน Di Angello Pizzeria (ดิแอง..",
  "ร้าน Box Cafe'",
  "ร้าน Pasang",
  "ร้านไก่ย่างภูแล",
  "ร้าน ๙ Cafe' Chiang Rai",
];
const List<String> name = [
  //เเครอด ผัก ผมไม้
  "พิพิธภัณฑ์บ้านดำ",
  "น้ำตกนางแลใน",
  "นาขั้นบันได",
  "ร้านทุ่งเคียงดอย & เคียงดอยคาเฟ่",
  "สวนสตอเบอร์รี่ชมดอย โฮมสเตย์",
  "โฮงฮอมผญ๋า โฮงยาหมอเมืองล้านนา..",
  "สวนคุณปู่สับปะรดอินทรีย์",
  "เครื่องปั้นดินเผาดอยดินแดง",
  "ชุมชุนบ้านป่าอ้อ5ชนเผ่ากระเหรี่ยงคอยาว",
  "ร้าน Some Sunday Magic",
  "ร้าน Give Green Farm House..",
  "ร้าน Di Angello Pizzeria (ดิแอง..",
  "ร้าน Box Cafe'",
  "ร้าน Pasang",
  "ร้านไก่ย่างภูแล",
  "ร้าน ๙ Cafe' Chiang Rai",
];
const List<String> history1 = [
  //เเครอด ผัก ผมไม้

  "สถานที่รวบรวมผลงานศิลปะของอาจารย์ถวัลย์ ดัชนี ศิลปินแห่งชาติสาขาทัศนศิลป์ (จิตรกรรม)..",
  "ตั้งอยู่บริเวณบ้านนางแลใน เป็นแหล่งน้ำหล่อเลี้ยงชาวบ้าน เพื่อการอุปโภค บริโภค หากเข้าไป..",
  "แหล่งท่องเที่ยวทางวัฒนธรรม “นาขั้นบันได สถานที่ปลูกข้าวในเขตภูเขาสูง โดยชาวเขาต้อง..",
  "ร้านทุ่งเคียงดอยตั้งอยู่บนทุ่งนาที่ลูกหลานได้รับสืบทอดมาจากบรรพบุรุษ ในช่วงฤดูทํานาคุณ..",
  "สวนสตอเบอร์รี่ชมดอย โฮมสเตย์แหล่งปลูกสตรอเบอร์รี่พันธุ์ดีของเชียงรายอีกแห่งหนึ่ง ด้วยการ..",
  "โฮงฮอมผญ๋า โฮงยาหมอเมืองล้านนา ตําบลนางแล ศูนย์เผยแพร่ความรู้ภูมิปัญญาแบบพื้นบ้าน..",
  "แหล่งเรียนรู้วิธีการปลูกสับปะรดพันธุ์สายน้ำาผึ้ง (นางแล) พร้อมชิมสับปะรดจากสวน เนื้อเนียน..",
  "เครื่องปั้นดินเผาดอยดินแดง แหล่งผลิตเครื่องปั้นดินเผาที่ดีที่สุดอีกแห่งหนึ่งของประเทศไทย..",
  "หมู่บ้าน 5 ชนเผ่ากระเหรี่ยงคอยาว สถานที่ท่องเที่ยวเชิงวัฒนธรรม ที่มีชนเผ่ากะเหรี่ยงคอยาว..",
  "ร้านอาหารรสชาติดี หลากหลายเมนูทั้งอาหารคาวหวาน โดดเด่นด้วยอาคารเหล็กสีขาวสไตล์โม..",
  "ร้านอาหารเพื่อสุขภาพ ผักอินทรีย์ ปลอดสารพิษ ไม่ใส่ผงชูรสทุกเมนู เมนูอาหารเจ มังสวิรัติ..",
  "Bookcase Space and Cafe เป็นพื้นที่เปิดกว้างสําหรับคนรักกาแฟ หนังสือ และมิตรภาพ..",
  "ร้านกาแฟขนาดเล็ก ตกแต่งด้วยสไตล์ Loft พร้อมมอบคุณภาพที่เกินราคาให้ทุกท่าน ร้าน..",
  "ร้านกาแฟ Pasang ร้านกาแฟที่นําเอาสับปะรดนางแลซึ่งเป็นผลไม้มีชื่อเสียงในท้องถิ่นมาประ..",
  "ร้านไก่ย่างภูแล ส้มตํา ไก่ย่างรสชาตินุ่มลิ้น พร้อมคอหมูย่าง หมูทอดแดดเดียว และอาหาร..",
  "ร้านกาแฟสไตล์ Loft บริการอาหารไทยและอาหารฝรั่ง ร้านอยู่ข้างธนาคาร ธกส สาขานาง..",
];
const List<String> history = [
  //เเครอด ผัก ผมไม้
  "สถานที่รวบรวมผลงานศิลปะของอาจารย์ถวัลย์ ดัชนี ศิลปินแห่งชาติสาขาทัศนศิลป์ (จิตรกรรม) บน พื้นที่กว่า 100 ไร่ ประกอบด้วยอาคารสถาปัตยกรรมกว่า 40 หลัง ซึ่งได้รับแรงบันดาลใจในการ ออกแบบที่แตกต่างกันตามลักษณะทางวิวัฒนาการและยุคสมัย ดังนี้ 1. กลุ่มวัฒนธรรมไม้ 2. กลุ่ม วัฒนธรรมอินเผา 3. กลุ่มวัฒนธรรมคอนกรีต 4. กลุ่มเรือนบริการและศาลา เป็นจุดหมายปลายทาง ของผู้แสวงหาแรงบันดาลใจทางศิลปะ",
  "ตั้งอยู่บริเวณบ้านนางแลใน เป็นแหล่งน้ำหล่อเลี้ยงชาวบ้าน เพื่อการอุปโภค บริโภค หากเข้าไปถึงต้น กําเนิดของแหล่งน้ำตกนางแลในจะพบกับธรรมชาติที่สวยงามเป็นอย่างมาก",
  "แหล่งท่องเที่ยวทางวัฒนธรรม “นาขั้นบันได สถานที่ปลูกข้าวในเขตภูเขาสูง โดยชาวเขาต้องขุดปรับ พื้นที่ตามไหล่เขาให้เป็นแปลงนาบันไดหลาย ๆ ขึ้น นาขั้นบันไดเป็นแหล่งท่องเที่ยวที่สวยงาม และมี กิจกรรมให้นักท่องเที่ยวเข้ามาเรียนรู้ในการทำนา เรียนรู้วิถีชีวิตของชนเผ่าลาหู่ และอาข่า",
  "ร้านทุ่งเคียงดอยตั้งอยู่บนทุ่งนาที่ลูกหลานได้รับสืบทอดมาจากบรรพบุรุษ ในช่วงฤดูทํานาคุณยาย (ครู หล้า) ได้พาหลานชายที่เติบโตในป่าคอนกรีตเดินเลาะตามคันนา เมื่อหลานชายเห็นต้นข้าว ปู ปลา และ หอย (เชอรี่) จึงตื่นเต้นสนใจ พร้อมกับคําถามมากมายคุณยายเกิดความคิดว่าสถานที่แห่งนี้น่าจะ เป็นแหล่งเรียนรู้และปลุกจิตสํานึกให้ลูกหลานชาวบารักถิ่นฐานบ้านเกิด รักอาชีพของบรรพบุรุษ รัก ธรรมชาติของท้องทุ่งนา คุณยายจึงสร้างฮ่างนา (กระท่อม) จากไม้ไผ่และทําสะพานทางเดินเลาะตาม คันนาต่อมามีนักท่องเที่ยวแวะเยี่ยมชมและอยากนั่งจิบกาแฟท่ามกลางธรรมชาติที่มีทั้งทุ่งนาและภูเขา คําว่า ทุ่งเคียงดอย จึงเกิดขึ้นมาในสถานที่แห่งนี้ ร้านทุ่งเคียงดอย & เคียงดอยคาเฟ เป็นร้านกาแฟ เล็ก ๆ ไว้คอยต้อนรับผู้มาเยือนนั่งจิบกาแฟบองดูดอยดัง (ชื่อภูเขา) ว่าดังจริงสมชื่อหรือไม่ต้องมา พิสูจน์",
  "สวนสตอเบอร์รี่ชมดอย โฮมสเตย์แหล่งปลูกสตรอเบอร์รี่พันธุ์ดีของเชียงรายอีกแห่งหนึ่ง ด้วยการปลูก แบบปลอดสารพิษจึงให้รสชาติหวานกรอบและปลอดภัย ใกล้กันมีแปลงดอกดาวเรืองสีสวยให้ชมตาม ช่วงฤดูกาล",
  "โฮงฮอมผญ๋า โฮงยาหมอเมืองล้านนา ตําบลนางแล ศูนย์เผยแพร่ความรู้ภูมิปัญญาแบบพื้นบ้านล้านนา ให้บริการแก่นักท่องเที่ยว ด้วยศาสตร์การรักษาแบบล้านนาโบราณ อาทิ การย่ำขาง ตอกเส้น เช็ด แหก ย่างสมุนไพร อบสมุนไพร จู้ยา เป่า แบบล้านนาโบราณ เป็นต้น",
  "แหล่งเรียนรู้วิธีการปลูกสับปะรดพันธุ์สายน้ำาผึ้ง (นางแล) พร้อมชิมสับปะรดจากสวน เนื้อเนียนละมุน ไม่มีเสี้ยนให้ระคายลิ้นเหมือนสับปะรดทั่วไป กลิ่นหอมหวานปานน้ำาผึ้ง เวลารับประกาusสชาติจะหวาน ชื่นใจแตกต่างจากสับปะรดทั่วไป ยืนยันความอร่อยจากการจดทะเบียน สิ่งบ่งชี้ทางภูมิศาสตร์ ว่า สับปะรดน้ําผึ้ง (นางแล) ต้องปลูกที่ตําบลนางแลเท่านั้น",
  "เครื่องปั้นดินเผาดอยดินแดง แหล่งผลิตเครื่องปั้นดินเผาที่ดีที่สุดอีกแห่งหนึ่งของประเทศไทย พร้อม ต้อนรับนักท่องเที่ยวด้วยห้องแสดงผลงานปั้นด้วยมือทุกชิ้น โดยใช้วัตถุดิบและแรงงานในท้องถิ่น ออกแบบโดยอาจารย์สมลักษณ์ ปันติบุญ",
  "หมู่บ้าน 5 ชนเผ่ากระเหรี่ยงคอยาว สถานที่ท่องเที่ยวเชิงวัฒนธรรม ที่มีชนเผ่ากะเหรี่ยงคอยาว ชนเผ่า อาน่า ชนเผ่าเย้า ชนเผ่าลาหู่ และชนเผ่ากระยอ อาศัยอยู่รวมในหมู่บ้าน ภายในหมู่บ้านมีการจัดแสดงงาน ศิลปะ วัฒนธรรม และเป็นแหล่งเรียนรู้วิถีชีวิตของกลุ่มชาติพันธุ์ต่าง ๆ",
  "ร้านอาหารรสชาติดี หลากหลายเมนูทั้งอาหารคาวหวาน โดดเด่นด้วยอาคารเหล็กสีขาวสไตล์โมเดิล ทาง เข้าร้านอยู่ในเส้นทางเดียวกับทางเข้าพิพิธภัณฑ์บ้านดํา ของอาจารย์ถวัลย์ ดัชนี",
  "ร้านอาหารเพื่อสุขภาพ ผักอินทรีย์ ปลอดสารพิษ ไม่ใส่ผงชูรสทุกเมนู เมนูอาหารเจ มังสวิรัติ อาหารพื้นเมือง เป็นร้านแบบให้ลูกค้าบริการด้วยตนเอง ทางเข้าร้านอยู่ในเส้นทางเดียวกับทางเข้าพิพิธภัณฑ์บ้านดํา ของอาจารย์ถวัลย์ ดัชนี",
  "Bookcase Space and Cafe เป็นพื้นที่เปิดกว้างสําหรับคนรักกาแฟ หนังสือ และมิตรภาพ ว่าด้วย กาแฟที่คัดสรรมาแล้วอย่างดี เมล็ดกาแฟที่ทางร้านเลือกใช้เป็นกาแฟอราบิก้าคั่วจากแหล่งต่าง ๆ ทั่วโลก อาทิ เปรู โคลัมเบีย เมียนมา (รัฐฉาน) ฟิลิปปินส์ อินโดนีเซีย เอธิโอเปีย และแน่นอน จากประเทศไทย ว่า กันว่า คนชงกาแฟเป็นหนึ่งในปัจจัยสําคัญที่มีผลโดยตรงต่อรสชาติของกาแฟ บาริสต้าของทางร้านเป็น นักเคมีที่อดีตเคยเป็นอาจารย์และนักวิจัยด้านชา การชงกาแฟของเธอจึงเปรียบเสมือนหนึ่งห้องทดลอง ต่างกันก็ตรงที่ใส่แง่มุมของความสุขเข้าไปในกาแฟทุกถ้วยที่ชงด้วยความพิถีพิถัน นอกจากนี้ทางร้านยัง มีอาหารบริการ เป็นพื้นที่จัดกิจกรรมทางสังคม เช่น การจัด workshop ต่างๆ อาทิ การทําหนังสือทํา มือ การทําสบู่ธรรมชาติ เป็นต้น",
  "ร้านกาแฟขนาดเล็ก ตกแต่งด้วยสไตล์ Loft พร้อมมอบคุณภาพที่เกินราคาให้ทุกท่าน ร้านอยู่ใกล้กับโรง พยาบาลกรุงเทพ สาขาเชียงราย ใกล้กับทางเข้าพิพิธภัณฑ์บ้านดํา ของอาจารย์ถวัลย์ ดัชนี",
  "ร้านกาแฟ Pasang ร้านกาแฟที่นําเอาสับปะรดนางแลซึ่งเป็นผลไม้มีชื่อเสียงในท้องถิ่นมาประยุกต์ทําเป็น กาแฟรสชาติแปลกใหม่ ดื่มด่ำกับกาแฟแก้วโปรด ภายในร้านที่มีสถาปัตยกรรมโครงสร้างเหล็กดีไซน์ ร่วมสมัย",
  "ร้านไก่ย่างภูแล ส้มตํา ไก่ย่างรสชาตินุ่มลิ้น พร้อมคอหมูย่าง หมูทอดแดดเดียว และอาหารท้องถิ่นหลาก หลายเมนู สถานที่ตั้งร้านอยู่ตรงข้ามกับโรงพยาบาลแม่ฟ้าหลวง จังหวัดเชียงราย",
  "ร้านกาแฟสไตล์ Loft บริการอาหารไทยและอาหารฝรั่ง ร้านอยู่ข้างธนาคาร ธกส สาขานางแล ตรงข้าม กับทางเข้าพิพิธภัณฑ์บ้านดํา ของอาจารย์ถวัลย์ ดัชนี",
];
const List<String> time_available = [
  "เปิดให้เข้าชมทุกวัน  ตั้งแต่เวลา 09.00-17.00 น.",
  "เปิดให้บริการ  ตั้งแต่เวลา 09.00-17.00 น.",
  "เปิดให้เข้าชมทุกวัน  ตั้งแต่เวลา 08.00-17.00 น.",
  "เปิดให้บริการ  ตั้งแต่เวลา 09.00-20.00 น.",
  "เปิดให้บริการ  ตั้งแต่เวลา 06.00 – 18.00 น.",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 09.00-17.00 น.",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 09.00-17.00 น.",
  "เปิดให้เข้าชม วันจันทร์ - วันเสาร์  ตั้งแต่เวลา 08.00-17.00 น.",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 07.00-19.00 น.",
  "เปิดให้บริการ ตั้งแต่เวลา 10.00 -20.00 น. (หยุดทุกวันพุธ) ",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 07.00 -19.00 น. ",
  "เปิดให้บริการ  ตั้งแต่เวลา 10.00-21.00 น. (หยุดทุกวันจันทร์)",
  "เปิดให้บริการวันจันทร์ - วันศุกร์  ตั้งแต่เวลา 07.00 -18.00 น. เปิดให้บริการวันเสาร์ - วันอาทิตย์  ตั้งแต่เวลา 08.00 -18.00 น.",
  "เปิดให้บริการวันจันทร์ - วันเสาร์  ตั้งแต่เวลา 09.00-18.00 น.  ",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 08.00 -17.00 น.",
  "เปิดให้บริการทุกวัน  ตั้งแต่เวลา 08.00-18.00 น.",
];
const List<String> place_des = [
  "พิพิธภัณฑ์บ้านดํา 333 บ้านแม่ปูคา หมู่ 13 ตําบล นางแล อําเภอเมืองเชียงราย  จังหวัดเชียงราย 57100",
  "บ้านนางแลใน หมู่ 7 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "บ้านนางแลใน หมู่ 7 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "571 บ้านนางแลใน หมู่ 7 ตำบลนางแล  อำเภอเมืองเชียงราย เชียงราย 57100",
  "341 หมู่ 7 บ้านนางแลใน ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย",
  "บ้านป่ารวก หมู่ 8 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "บ้านป่าซางวิวัฒน์ หมู่ 10 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "49 บ้านป่าอ้อ หมู่ 6 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "บ้านป่าอ้อ หมู่ 6 ตำบลนางแล อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "280 บ้านแม่ปูคา หมู่ 13 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "300 บ้านแม่ปูคา หมู่ 3 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "195 บ้านนางแล หมู่ 2 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "241 บ้านแม่ปูคา หมู่ 13 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "279 บ้านป่าซางวิวัฒน์ หมู่ 10 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "165 บ้านป่าซางวิวัฒน์ หมู่ 10 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
  "44 บ้านนางแล หมู่ 2 ตำบลนางแล  อำเภอเมืองเชียงราย จังหวัดเชียงราย 57100",
];

const List<String> note = [
  "http://www.thawan-duchanee.com  อัตราค่าเข้าชม 80 บาท ทั้งชาวไทย และชาวต่างชาติ",
  "http://www.nanglae.go.th/ ไม่มีการเก็บค่าบริการ ",
  "http://www.nanglae.go.th/ ติดต่อสอบถามเพิ่มเติม ",
  "https://www.facebook.com/tungkiengdoi/ ระยะเวลาทำนาครั้งที่ 1 เริ่มดำนาเดือนกรกฎาคม เก็บเกี่ยวปลายเดือนพฤศจิกายนระยะเวลาทำนาครั้งที่ 2 เริ่มดำนาเดือนมกราคม เก็บเกี่ยวปลายเดือนพฤษภาคมเมนูแนะนำ ไอศครีมสับปะรด",
  "https://web.facebook.com/pg/สวนสตรอเบอร์รี่-ชมดอย-308206636041016/photos/?ref=page_internal ไม่มีค่าบริการชมสวนติดต่อสอบถามบริการห้องพักและที่พักแบบเต็นท์ (รวมอาหารเช้า)ช่วงเดือน ตุลาคม - มีนาคม เปิดชมสวนสตรอเบอร์รี่ช่วงเดือน เมษายน - กันยายน เปิดชมลานดอกดาวเรือง ",
  "https://www.facebook.com/%E0%B9%82%E0%B8%AE%E0%B8%87%E0%B8%AE%E0%B8%AD%E0%B8%A1%E0%B8%9C%E0%B8%8D%E0%B9%8B%E0%B8%B2-%E0%B9%82%E0%B8%AE%E0%B8%87%E0%B8%A2%E0%B8%B2%E0%B8%AB%E0%B8%A1%E0%B8%AD%E0%B9%80%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%87%E0%B8%A5%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%99%E0%B8%B2-%E0%B8%93%E0%B8%A8%E0%B8%B9%E0%B8%99%E0%B8%A2%E0%B9%8C%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%8A%E0%B8%B8%E0%B8%A1%E0%B8%8A%E0%B8%99%E0%B8%95%E0%B8%B3%E0%B8%9A%E0%B8%A5%E0%B8%99%E0%B8%B2%E0%B8%87%E0%B9%81%E0%B8%A5-1409981902398090/ ติดต่อสอบถามเพิ่มเติมเพื่อรับบริการในจุดให้บริการเครือข่ายการย่างสมุนไพรและอบสมุนไพรมีผลต่อการควบคุมน้ำหนัก",
  "https://www.facebook.com/%E0%B8%97%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%8A%E0%B8%B8%E0%B8%A1%E0%B8%8A%E0%B8%99%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%9B%E0%B9%88%E0%B8%B2%E0%B8%8B%E0%B8%B2%E0%B8%87%E0%B8%A7%E0%B8%B4%E0%B8%A7%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B9%8C-193802381202715/ ช่วงเวลาที่สับปะรดมีรสชาติดีที่สุด คือ  ช่วงเดือนเมษายน – มิถุนายน",
  "http://www.dddpottery.com/index.html มีร้านกาแฟให้บริการสำหรับนักท่องเที่ยว",
  "http://www.unionhilltribe.com/  นักท่องเที่ยวชาวต่างชาติ 300 บาท/คน คนไทย 200 บาท/คน",
  "https://www.facebook.com/Somesundaymagic/ เมนูแนะนำ ข้าวซอยไก่กะทิ",
  "https://www.facebook.com/givegreenfarm/ เปิดสอนทำอาหาร (Cooking Class)เมนูแนะนำ น้ำเงี้ยว",
  "https://www.facebook.com/diangelloitalianpizza เมนูแนะนำ พิซซ่าแป้งบางกรอบ หน้าสับปะรด แฮม ชีส",
  "Facebook: BoxCafe Chiangrai เมนูแนะนำ นมคาราเมล",
  "https://www.facebook.com/pasangchiangrai/",
  "Facebook: chickenphulae เมนูแนะนำ ส้มตำปูปลาร้า ไก่ย่าง",
  "Facebook: 9 café Chiangrai เมนูแนะนำ กาแฟดำ",
];
const List<String> phone = [
  "053-776-333",
  "053-706-017",
  "053-706-017",
  "088-700-0842 088-884-5533",
  "082-193-2423",
  "090-280-6924",
  "090-317-5429",
  "053-705-291",
  "053-705-337 081-993-3827",
  "083-5814459",
  "081-090-1805",
  "080-286-8895 093-593-0475",
  "08-0110-5665",
  "063-783-3388",
  "081-486-1424",
  "089-758-1198"
];

Map<int, Color> color = {
  50: Color.fromRGBO(147, 215, 228, .1),
  100: Color.fromRGBO(147, 215, 228, .2),
  200: Color.fromRGBO(147, 215, 228, .3),
  300: Color.fromRGBO(147, 215, 228, .4),
  400: Color.fromRGBO(147, 215, 228, .5),
  500: Color.fromRGBO(147, 215, 228, .6),
  600: Color.fromRGBO(147, 215, 228, .7),
  700: Color.fromRGBO(147, 215, 228, .8),
  800: Color.fromRGBO(147, 215, 228, .9),
  900: Color.fromRGBO(147, 215, 228, 1)
};
