import 'dart:ui';

List l = [];
List m = [];
List n = [];
List button1 = [];

Map sets = {
  0: [19.992118, 99.860694],
  1: [20.044707, 99.828704],
  2: [20.064509, 99.811011],
  3: [20.027004, 99.844637],
  4: [20.033889, 99.836202],
  5: [20.033839, 99.855696],
  6: [20.015930, 99.520620],
  7: [20.017781, 99.882237],
  8: [20.019234, 99.889824],
  9: [19.992970, 99.861781],
  10: [19.992596, 99.859079],
  11: [19.994223, 99.864782],
  12: [19.992283, 99.863845],
  13: [20.031752, 99.872231],
  14: [20.032092, 99.873869],
  15: [19.993666, 99.864708],
};

const List u = [
  images,
  images1,
  images2,
  images3,
  images4,
  images5,
  images6,
  images7,
  images8,
  images9,
  images10,
  images11,
  images12,
  images13,
  images14,
  images15,
];
const List<String> imagess = [
  "assets/images/im/imagess/000.jpg",
  "assets/images/im/imagess/001.jpg",
  "assets/images/im/imagess/002.jpg",
  "assets/images/im/imagess/003.jpg",
  "assets/images/im/imagess/004.jpg",
  "assets/images/im/imagess/005.jpg",
  "assets/images/im/imagess/006.jpg",
  "assets/images/im/imagess/007.jpg",
  "assets/images/im/imagess/008.jpg",
  "assets/images/im/imagess/009.jpg",
  "assets/images/im/imagess/010.jpg",
  "assets/images/im/imagess/011.jpg",
  "assets/images/im/imagess/012.jpg",
  "assets/images/im/imagess/013.jpg",
  "assets/images/im/imagess/014.jpg",
  "assets/images/im/imagess/015.jpg",
  // target
];

const List<String> images = [
  // target
  "assets/images/im/images/000.jpg",
  "assets/images/im/images/001.jpg",
  "assets/images/im/images/002.jpg",
  "assets/images/im/images/003.jpg",
  "assets/images/im/images/004.jpg",
  "assets/images/im/images/005.jpg",
  "assets/images/im/images/006.jpg",
  "assets/images/im/images/007.jpg",
  "assets/images/im/images/008.jpg",
  "assets/images/im/images/009.jpg",
  "assets/images/im/images/010.jpg",
  "assets/images/im/images/011.jpg",
  "assets/images/im/images/012.jpg",
  "assets/images/im/images/013.jpg",
  "assets/images/im/images/014.jpg",
  "assets/images/im/images/015.jpg",
  // target
];
const List<String> images1 = [
  "assets/images/im/images1/000.jpg",
  "assets/images/im/images1/001.jpg",
  "assets/images/im/images1/002.jpg",
  "assets/images/im/images1/003.jpg",
  "assets/images/im/images1/004.jpg",
  "assets/images/im/images1/005.jpg",
  "assets/images/im/images1/006.jpg",
  "assets/images/im/images1/007.jpg",
  // target
];
const List<String> images2 = [
  // target
  "assets/images/im/images2/000.jpg",
  "assets/images/im/images2/001.jpg",
  "assets/images/im/images2/002.jpg",
  "assets/images/im/images2/003.jpg",
  "assets/images/im/images2/004.jpg",
  "assets/images/im/images2/005.jpg",
  "assets/images/im/images2/006.jpg",
];
const List<String> images3 = [
  // target
  "assets/images/im/images3/000.jpg",
  "assets/images/im/images3/001.jpg",
  "assets/images/im/images3/002.jpg",
  "assets/images/im/images3/003.jpg",
  "assets/images/im/images3/004.jpg",
  "assets/images/im/images3/005.jpg",
  "assets/images/im/images3/006.jpg",
  "assets/images/im/images3/007.jpg",
  "assets/images/im/images3/008.jpg",
  "assets/images/im/images3/009.jpg",
  "assets/images/im/images3/010.jpg",
  "assets/images/im/images3/011.jpg",
  "assets/images/im/images3/012.jpg",
  "assets/images/im/images3/013.jpg",
  "assets/images/im/images3/014.jpg",
  "assets/images/im/images3/015.jpg",
  "assets/images/im/images3/016.jpg",
  "assets/images/im/images3/017.jpg",
];
const List<String> images4 = [
  // target
  "assets/images/im/images4/000.jpg",
  "assets/images/im/images4/001.jpg",
  "assets/images/im/images4/002.jpg",
  "assets/images/im/images4/003.jpg",
  "assets/images/im/images4/004.jpg",
  "assets/images/im/images4/005.jpg",
  "assets/images/im/images4/006.jpg",
  "assets/images/im/images4/007.jpg",
  "assets/images/im/images4/008.jpg",
  "assets/images/im/images4/009.jpg",
  "assets/images/im/images4/010.jpg",
  "assets/images/im/images4/011.jpg",
  "assets/images/im/images4/012.jpg",
  "assets/images/im/images4/013.jpg",
  "assets/images/im/images4/014.jpg",
  "assets/images/im/images4/015.jpg",
  "assets/images/im/images4/016.jpg",
  "assets/images/im/images4/017.jpg",
  "assets/images/im/images4/018.jpg",
  "assets/images/im/images4/019.jpg",
];
const List<String> images5 = [
  // target
  "assets/images/im/images5/000.jpg",
  "assets/images/im/images5/001.jpg",
  "assets/images/im/images5/002.jpg",
  "assets/images/im/images5/003.jpg",
  "assets/images/im/images5/004.jpg",
  "assets/images/im/images5/005.jpg",
  "assets/images/im/images5/006.jpg",
  "assets/images/im/images5/007.jpg",
  "assets/images/im/images5/008.jpg",
  "assets/images/im/images5/009.jpg",
  "assets/images/im/images5/010.jpg",
  "assets/images/im/images5/011.jpg",
  "assets/images/im/images5/012.jpg",
  "assets/images/im/images5/013.jpg",
  "assets/images/im/images5/014.jpg",
  "assets/images/im/images5/015.jpg",
  "assets/images/im/images5/016.jpg",
  "assets/images/im/images5/017.jpg",
];
const List<String> images6 = [
  // target
  "assets/images/im/images6/000.jpg",
  "assets/images/im/images6/001.jpg",
  "assets/images/im/images6/002.jpg",
  "assets/images/im/images6/003.jpg",
  "assets/images/im/images6/004.jpg",
  "assets/images/im/images6/005.jpg",
  "assets/images/im/images6/006.jpg",
];
const List<String> images7 = [
  // target
  "assets/images/im/images7/000.jpg",
  "assets/images/im/images7/001.jpg",
  "assets/images/im/images7/002.jpg",
  "assets/images/im/images7/003.jpg",
  "assets/images/im/images7/004.jpg",
  "assets/images/im/images7/005.jpg",
  "assets/images/im/images7/006.jpg",
  "assets/images/im/images7/007.jpg",
  "assets/images/im/images7/008.jpg",
  "assets/images/im/images7/009.jpg",
  "assets/images/im/images7/010.jpg",
  "assets/images/im/images7/011.jpg",
  "assets/images/im/images7/012.jpg",
  "assets/images/im/images7/013.jpg",
  "assets/images/im/images7/014.jpg",
  "assets/images/im/images7/015.jpg",
  "assets/images/im/images7/016.jpg",
  "assets/images/im/images7/017.jpg",
];
const List<String> images8 = [
  // target
  "assets/images/im/images8/000.jpg",
  "assets/images/im/images8/001.jpg",
  "assets/images/im/images8/002.jpg",
  "assets/images/im/images8/003.jpg",
  "assets/images/im/images8/004.jpg",
  "assets/images/im/images8/005.jpg",
  "assets/images/im/images8/006.jpg",
  "assets/images/im/images8/007.jpg",
  "assets/images/im/images8/008.jpg",
  "assets/images/im/images8/009.jpg",
  "assets/images/im/images8/010.jpg",
  "assets/images/im/images8/011.jpg",
  "assets/images/im/images8/012.jpg",
  "assets/images/im/images8/013.jpg",
  "assets/images/im/images8/014.jpg",
  "assets/images/im/images8/015.jpg",
  "assets/images/im/images8/016.jpg",
  "assets/images/im/images8/017.jpg",
];
const List<String> images9 = [
  // target
  "assets/images/im/images9/000.jpg",
  "assets/images/im/images9/001.jpg",
  "assets/images/im/images9/002.jpg",
  "assets/images/im/images9/003.jpg",
  "assets/images/im/images9/004.jpg",
  "assets/images/im/images9/005.jpg",
  "assets/images/im/images9/006.jpg",
  "assets/images/im/images9/007.jpg",
  "assets/images/im/images9/008.jpg",
  "assets/images/im/images9/009.jpg",
  "assets/images/im/images9/010.jpg",
  "assets/images/im/images9/011.jpg",
  "assets/images/im/images9/012.jpg",
  "assets/images/im/images9/013.jpg",
  "assets/images/im/images9/014.jpg",
  "assets/images/im/images9/015.jpg",
  "assets/images/im/images9/016.jpg",
  "assets/images/im/images9/017.jpg",
  "assets/images/im/images9/018.jpg",
  "assets/images/im/images9/019.jpg",
  "assets/images/im/images9/020.jpg",
];
const List<String> images10 = [
  // target
  "assets/images/im/images10/000.jpg",
  "assets/images/im/images10/001.jpg",
  "assets/images/im/images10/002.jpg",
  "assets/images/im/images10/003.jpg",
  "assets/images/im/images10/004.jpg",
  "assets/images/im/images10/005.jpg",
  "assets/images/im/images10/006.jpg",
  "assets/images/im/images10/007.jpg",
  "assets/images/im/images10/008.jpg",
  "assets/images/im/images10/009.jpg",
  "assets/images/im/images10/010.jpg",
  "assets/images/im/images10/011.jpg",
];
const List<String> images11 = [
  // target
  "assets/images/im/images11/000.jpg",
  "assets/images/im/images11/001.jpg",
  "assets/images/im/images11/002.jpg",
  "assets/images/im/images11/003.jpg",
  "assets/images/im/images11/004.jpg",
  "assets/images/im/images11/005.jpg",
  "assets/images/im/images11/006.jpg",
  "assets/images/im/images11/007.jpg",
  "assets/images/im/images11/008.jpg",
  "assets/images/im/images11/009.jpg",
  "assets/images/im/images11/010.jpg",
  "assets/images/im/images11/011.jpg",
  "assets/images/im/images11/012.jpg",
  "assets/images/im/images11/013.jpg",
  "assets/images/im/images11/014.jpg",
];
const List<String> images12 = [
  // target
  "assets/images/im/images12/000.jpg",
  "assets/images/im/images12/001.jpg",
  "assets/images/im/images12/002.jpg",
  "assets/images/im/images12/003.jpg",
  "assets/images/im/images12/004.jpg",
  "assets/images/im/images12/005.jpg",
  "assets/images/im/images12/006.jpg",
  "assets/images/im/images12/007.jpg",
  "assets/images/im/images12/008.jpg",
  "assets/images/im/images12/009.jpg",
  "assets/images/im/images12/010.jpg",
  "assets/images/im/images12/011.jpg",
  "assets/images/im/images12/012.jpg",
  "assets/images/im/images12/013.jpg",
];
const List<String> images13 = [
  // target
  "assets/images/im/images13/000.jpg",
  "assets/images/im/images13/001.jpg",
  "assets/images/im/images13/002.jpg",
  "assets/images/im/images13/003.jpg",
  "assets/images/im/images13/004.jpg",
  "assets/images/im/images13/005.jpg",
  "assets/images/im/images13/006.jpg",
  "assets/images/im/images13/007.jpg",
  "assets/images/im/images13/008.jpg",
  "assets/images/im/images13/009.jpg",
  "assets/images/im/images13/010.jpg",
  "assets/images/im/images13/011.jpg",
  "assets/images/im/images13/012.jpg",
];
const List<String> images14 = [
  // target
  "assets/images/im/images14/000.jpg",
  "assets/images/im/images14/001.jpg",
  "assets/images/im/images14/002.jpg",
  "assets/images/im/images14/003.jpg",
  "assets/images/im/images14/004.jpg",
  "assets/images/im/images14/005.jpg",
  "assets/images/im/images14/006.jpg",
  "assets/images/im/images14/007.jpg",
  "assets/images/im/images14/008.jpg",
  "assets/images/im/images14/009.jpg",
  "assets/images/im/images14/010.jpg",
  "assets/images/im/images14/011.jpg",
  "assets/images/im/images14/012.jpg",
  "assets/images/im/images14/013.jpg",
];
const List<String> images15 = [
  // target
  "assets/images/im/images15/000.jpg",
  "assets/images/im/images15/001.jpg",
  "assets/images/im/images15/002.jpg",
  "assets/images/im/images15/003.jpg",
  "assets/images/im/images15/004.jpg",
  "assets/images/im/images15/005.jpg",
  "assets/images/im/images15/006.jpg",
  "assets/images/im/images15/007.jpg",
  "assets/images/im/images15/008.jpg",
  "assets/images/im/images15/009.jpg",
  "assets/images/im/images15/010.jpg",
  "assets/images/im/images15/011.jpg",
  "assets/images/im/images15/012.jpg",
  "assets/images/im/images15/013.jpg",
  "assets/images/im/images15/014.jpg",
  "assets/images/im/images15/015.jpg",
  "assets/images/im/images15/016.jpg",
  "assets/images/im/images15/017.jpg",
  "assets/images/im/images15/018.jpg",
];

const List<String> hardtext = [
  //เเครอด ผัก ผมไม้
  "Baandam (Black House) Museum",
  "Nang Lae Nai Waterfall",
  "Rice Terraces",
  "Tung Kieng Doi Restaurant & Kieng Doi Café ",
  "Strawberry Garden Chom Doi Homestay",
  "Hong Hom Pa Ya, Hong Ya Moh Muang Lanna, Nang Lae Sub-district",
  "Suan Khun Poo (Grandfather’s Graden)Organic Pineapples",
  "Doi Din Daeng Pottery",
  "Ban Pa Oh Community ๕ Long Neck Karen Hilltribes",
  "Some Sunday Magic Restaurant",
  "Give Green Farm House Restaurant ",
  "Di Angello Pizzeria Restaurant",
  "Box Café",
  "Pasang Coffee Shop",
  "Phu Lae Grilled Chicken Shop",
  "๙ Café Chiang Rai ",
];

const List<String> hardtext1 = [
  //เเครอด ผัก ผมไม้
  "Baandam (Black House) ..",
  "Nang Lae Nai Waterfall",
  "Rice Terraces",
  "Tung Kieng Doi Restaurant ..",
  "Strawberry Garden Chom ..",
  "Hong Hom Pa Ya, Hong Ya ..",
  "Suan Khun Poo ..",
  "Doi Din Daeng Pottery",
  "Ban Pa Oh Community ๕ ..",
  "Some Sunday Magic ..",
  "Give Green Farm House .. ",
  "Di Angello Pizzeria ..",
  "Box Café",
  "Pasang Coffee Shop",
  "Phu Lae Grilled Chicken Shop",
  "๙ Café Chiang Rai ",
];

const List<String> name = [
  //เเครอด ผัก ผมไม้
  "Baandam (Black House) Museum",
  "Nang Lae Nai Waterfall",
  "Rice Terraces",
  "Tung Kieng Doi Restaurant & Kieng Doi Café ",
  "Strawberry Garden Chom Doi Homestay",
  "Hong Hom Pa Ya, Hong Ya Moh Muang Lanna, Nang Lae Sub-district",
  "Suan Khun Poo (Grandfather’s Graden)Organic Pineapples",
  "Doi Din Daeng Pottery",
  "Ban Pa Oh Community ๕ Long Neck Karen Hilltribes",
  "Some Sunday Magic Restaurant",
  "Give Green Farm House Restaurant ",
  "Di Angello Pizzeria Restaurant",
  "Box Café",
  "Pasang Coffee Shop",
  "Phu Lae Grilled Chicken Shop",
  "๙ Café Chiang Rai ",
];
const List<String> history = [
  //เเครอด ผัก ผมไม้
  "The Art Gallery of AjarnThawan Duchanee, National Artist in Visual Arts (Painting), on the area of over 100 rais consists of over 40 architectural buildings inspired by different designs according to the evolution and the era as follows: ๑) Wood culture group, ๒) Pottery culture group, ๓) Concrete culture group, and ๔) Service house and pavillon group. This tourist attraction is also the destination of those seeking artistic inspiration.",
  "Located in the area of Ban Nang Lae Nai, Nang Lae Nai Waterfall is the water source of villagers for their consumption. If tourists come to the origin of Nang Lae Nai Waterfall, they will experience a very beautiful nature.",
  "The cultural attractions called, “Rice Terraces”are the rice fields in the high mountain zone. The hilltribes have to dig up the hillside area to become the rice terraces. Here are so beautiful tourist attractions and there are lots of activities for tourists to learn how to do rice fields as well as to learn the lifestyle of the Lahu and Akha tribes. ",
  "Tung Kieng Doi Restaurant is located on the field where the children have inherited from their ancestors. During the farming season, the grandmother (the teacher named,“Lah”) took her nephew growing in a concrete forest to walk along the ridge. When her nephew saw rice, crabs, fish, and mussels (cherry), he was so excited with many questions.        The grandmother thought that this place should be a source of learning and raise awareness for the children of the peasant family to love home, to love the career of the ancestors, and to love the nature of the field,  so the grandmother built the Hang Na (pavilion) from the bamboo and made a walkway along the ridge. Later, visitors have visited and would like to sip coffee in the midst of nature surrounding with fields and mountains, so, the words, “Tung Kieng Doi” happened in this place. Tung Kieng Doi Restaurant & Kieng Doi Café is a small coffee shop to welcome visitors to sit and sip coffee and watch the mountain (Doi) that the real name must be proven.",
  "Strawberry Garden Chom Doi Homestay is another good place to grow good species of strawberries in Chiangrai with the non-toxic growth,  so the taste of them is so sweet and safe. Close to them there are beautiful and colorful marigold flowers to see during the season.",
  "Hong Hom Pa Ya, Hong Ya Moh Muang Lanna, Nang Lae Sub-district",
  "This learning source is about how to grow honey pineapples (Nang Lae) and to taste fresh and smooth pineapples from the garden. The smell is sweet like honey. The taste is so sweet and it is different from general pineapples. They confirm the deliciousness of the registration, Geographical Indication that the honey pineapples (Nang Lae) must be planted in Nang Lae Sub-district only.",
  "Doi Din Daeng Pottery is one of the best pottery production sites in Thailand. Welcome all visitors to the hand-made sculpture workshop and exhibitions used raw materials and local labors and designed by Ajarn Somlak Puntiboon.",
  "Five long neck Karen hilltribe villages are cultural attractions including the long neck Karen tribe, the Akha tribe, the Yao tribe, the Lahu tribe and the Kra Yor tribe living in the village. In the village, there is an exhibit of art and culture and here is a source of learning about the way of life of different ethnic groups.",
  "This restaurant has clean foods with good tastes. It is characterized by a white steel structure and modern style. The entrance to the restaurant is in the same way as the entrance of Baandam (Black House) Museum of Ajarn Thawan Duchanee.",
  "This restaurant serves only healthy foods beacause it uses organic vegetables and it does not put any MSG in every menu. Vegetarian food is served locally. It is also a self - service restaurant. The entrance to the restaurant is in the same way as the entrance of Baandam (Black House) Museum of Ajarn Thawan Duchanee.",
  "The home - made pizza with thin crust in Italian style by using flour and cheese from the Italian chef. Each pizza is fresh and new. Most of the ingredients are imported from Italy and serve other Italian dishes, including pasta, baked beans, lasagna, salads and spaghetti. The shop is next to Bank for Agriculture and Agricultural Cooperatives (Nang Lae Branch) across from the entrance of Baandam (Black House) Museum of Ajarn Thawan Duchanee.",
  "Here is a small coffee shop to be decorated with Loft style and offered the quality, overpriced to all. This shop is near Bangkok Hospital (Chiangrai Branch) nearby the entrance of Baandam (Black House) Museum of Ajarn Thawan Duchanee.",
  "Pasang Coffee Shop is the coffee shop that brought Nang Lae pineapple, which is a famous fruit in the local area to be applied to a new exotic coffee. Indulge in favorite coffee. The shop has a contemporary architectural steel structure.",
  "Phu Lae Grilled Chicken Shop provides papaya spicy salad, yummy grilled chicken together with grilled pork neck, fried pork, and many local dishes. The shop is located opposite Mae Fah Luang Hospital, Chiangrai Province.",
  "The ๙ Café Chiang Rai is the coffee shop in Loft style served Thai and western foods. The shop is located beside Bank for Agriculture and Agricultural Cooperatives (Nang Lae Branch) opposite the entrance of Baandam (Black House) Museum of Ajarn Thawan Duchanee.",
];

const List<String> history1 = [
  //เเครอด ผัก ผมไม้
  "The Art Gallery of AjarnThawan Duchanee, National Artist in Visual Arts ..",
  "Located in the area of Ban Nang Lae Nai, Nang Lae Nai Waterfall is the ..",
  "The cultural attractions called, “Rice Terraces”are the rice fields in ..",
  "Tung Kieng Doi Restaurant is located on the field where the children have ..",
  "Strawberry Garden Chom Doi Homestay is another good place to grow good ..",
  "Hong Hom Pa Ya, Hong Ya Moh Muang Lanna, Nang Lae Sub-district",
  "This learning source is about how to grow honey pineapples (Nang Lae) and ..",
  "Doi Din Daeng Pottery is one of the best pottery production sites in ..",
  "Five long neck Karen hilltribe villages are cultural attractions including ..",
  "This restaurant has clean foods with good tastes. It is characterized by a ..",
  "This restaurant serves only healthy foods beacause it uses organic ..",
  "The home - made pizza with thin crust in Italian style by using flour ..",
  "Here is a small coffee shop to be decorated with Loft style and offered ..",
  "Pasang Coffee Shop is the coffee shop that brought Nang Lae pineapple, ..",
  "Phu Lae Grilled Chicken Shop provides papaya spicy salad, yummy grilled ..",
  "The ๙ Café Chiang Rai is the coffee shop in Loft style served Thai and ..",
];

const List<String> time_available = [
  "Open daily  from ๐๙.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๙.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๘.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๙.๐๐ – ๒๐.๐๐",
  "Open daily  from ๐๖.๐๐ – ๑๘.๐๐ ",
  "Open daily  from ๐๙.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๙.๐๐ – ๑๗.๐๐",
  "Open on  Monday - Saturday  from ๐๘.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๗.๐๐ – ๑๙.๐๐",
  "Open  from ๑๐.๐๐ – ๒๐.๐๐ น.  (Close every Wednesday)",
  "Open daily  from ๐๗.๐๐ – ๑๙.๐๐",
  "Open daily  from ๑๐.๐๐ – ๒๑.๐๐  (Close every Monday)",
  "Open on Monday – Friday  from ๐๗.๐๐ – ๑๘.๐๐ Open on Saturday – Sunday  from ๐๘.๐๐ – ๑๘.๐๐",
  "Open on Monday – Saturday  from ๐๙.๐๐ – ๑๘.๐๐",
  "Open daily  from ๐๘.๐๐ – ๑๗.๐๐",
  "Open daily  from ๐๘.๐๐ – ๑๘.๐๐",
];
const List<String> place_des = [
  "Baandam (Black House) Museum ๓๓๓ Ban Mae Pu Ka Moo ๑๓ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Nang Lae Nai Moo ๗ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Nang Lae Nai Moo ๗ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๕๗๑ Ban Nang Lae Nai Moo ๗ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๓๔๑ Moo ๗ Ban Nang Lae Nai, Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Pa Ruak Moo ๘ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Pa Sang Wiwat Moo ๑๐ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๔๙ Ban Pa Oh Moo ๖ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Pa Oh Moo ๖ Nang Lae, Muangchiangrai,Chiangrai ๕๗๑๐๐",
  "๒๘๐ Ban Mae Pu Ka Moo ๑๓ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๓๐๐ Ban Mae Pu Ka Moo ๓ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๑๙๕ Ban Nag Lae Moo ๒ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๒๔๑ Ban Mae Pu Ka Moo ๑๓ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๒๗๙ Ban Pa Sang Wiwat Moo ๑๐ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "๑๖๕ Ban Pa Sang Wiwat Moo ๑๐ Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
  "Ban Nang Lae Moo 2 Nang Lae, Muangchiangrai, Chiangrai ๕๗๑๐๐",
];

const List<String> note = [
  "http://www.thawan-duchanee.com  Admission fee ๘๐ baht per  person both Thais and foreigners",
  "http://www.nanglae.go.th/  No service charges",
  "http://www.nanglae.go.th/  Ask for more information",
  "https://www.facebook.com/tungkiengdoi/  Duration of farming the 1st time beginning doing in July and harvesting by the end of November Duration of farming the 2nd time beginning doing in January and harvesting by the end of May Recommended menu : Pineapple ice-cream",
  "https://web.facebook.com/pg/สวนสตรอเบอร์รี่-ชมดอย-308206636041016/photos/?ref=page_internal No fees for visiting the garden Ask for more information about room and tent services(breakfast included) Open the strawberry garden during October - March Open the Marigold flower field during April - September",
  "https://www.facebook.com/%E0%B9%82%E0%B8%AE%E0%B8%87%E0%B8%AE%E0%B8%AD%E0%B8%A1%E0%B8%9C%E0%B8%8D%E0%B9%8B%E0%B8%B2-%E0%B9%82%E0%B8%AE%E0%B8%87%E0%B8%A2%E0%B8%B2%E0%B8%AB%E0%B8%A1%E0%B8%AD%E0%B9%80%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%87%E0%B8%A5%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%99%E0%B8%B2-%E0%B8%93%E0%B8%A8%E0%B8%B9%E0%B8%99%E0%B8%A2%E0%B9%8C%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%8A%E0%B8%B8%E0%B8%A1%E0%B8%8A%E0%B8%99%E0%B8%95%E0%B8%B3%E0%B8%9A%E0%B8%A5%E0%B8%99%E0%B8%B2%E0%B8%87%E0%B9%81%E0%B8%A5-1409981902398090/ Contact your network service provider for more information.Grilling herbs and herbal remedies affect weight control.",
  "https://www.facebook.com/%E0%B8%97%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%8A%E0%B8%B8%E0%B8%A1%E0%B8%8A%E0%B8%99%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%9B%E0%B9%88%E0%B8%B2%E0%B8%8B%E0%B8%B2%E0%B8%87%E0%B8%A7%E0%B8%B4%E0%B8%A7%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B9%8C-193802381202715/ The best time to taste pineapple is from April – June.",
  "http://www.dddpottery.com/index.html  A coffee shop is available for tourists.",
  "http://www.unionhilltribe.com/  Foreign tourists : ๓๐๐ baht/person, Thai tourists : ๒๐๐ baht/person",
  "https://www.facebook.com/Somesundaymagic/  Recommended Dish : Khao Soi Chicken with coconut milk",
  "https://www.facebook.com/givegreenfarm/ Cooking School (Cooking Class)Recommended Dish : Khanom Jin Nam Ngiao(Rice noodles with spicy pork sauce)",
  "https://www.facebook.com/diangelloitalianpizza  Recommended Menu : Pizza with thin crust covering with pineapple, ham, and cheese",
  "Facebook: BoxCafe Chiangrai Recommended Menu : Caramel milk",
  "https://www.facebook.com/pasangchiangrai/  Pasang Coffee Shop has a good coffee served with honey pineapple (Nang Lae),which will be released and will havethe best taste during the months of April – June. Recommended Menu: Nang Lae Pineapple coffee",
  "Facebook: chickenphulae Recommended Menu : Papaya spicy salad,Grilled chicken",
  "Facebook:๙ café Chiangrai Recommended Menu : Black coffee",
];
const List<String> phone = [
  "053-776-333",
  "053-706-017",
  "053-706-017",
  "088-700-0842 088-884-5533",
  "082-193-2423",
  "090-280-6924",
  "090-317-5429",
  "053-705-291",
  "053-705-337 081-993-3827",
  "083-5814459",
  "081-090-1805",
  "080-286-8895 093-593-0475",
  "08-0110-5665",
  "063-783-3388",
  "081-486-1424",
  "089-758-1198"
];

Map<int, Color> color = {
  50: Color.fromRGBO(147, 215, 228, .1),
  100: Color.fromRGBO(147, 215, 228, .2),
  200: Color.fromRGBO(147, 215, 228, .3),
  300: Color.fromRGBO(147, 215, 228, .4),
  400: Color.fromRGBO(147, 215, 228, .5),
  500: Color.fromRGBO(147, 215, 228, .6),
  600: Color.fromRGBO(147, 215, 228, .7),
  700: Color.fromRGBO(147, 215, 228, .8),
  800: Color.fromRGBO(147, 215, 228, .9),
  900: Color.fromRGBO(147, 215, 228, 1)
};
